### ISSUE TITLE
Extending details for error NodeCreationFailure

### ISSUE THREAD

**Issue by browseman** [awsdocs/amazon-eks-user-guide#275]
Found out that a missing subnet from the VPC route table association can cause the exact same failure. Even if the rest of the possible causes are checked and not true, still had the same error. Possibly it will be useful for someone else, that have the same miss-configuration to spot the problem.
In my case I created a VPC with 3 subnets spread in 3 AZ, but by mistake in the route table association I put only two of the subnets. When deployed EKS cluster in this VPC, depending on the amount of nodes used in the deployment, I got sporadic behavior. Some times the deployment was successful from the first try, other times I had to re-deploy to pass successfully.
Opening an issue because I'm not sure, if such information will be useful for the documentation page. Also I don't know how to formulate if shortly, so that is fitting the document correctly.

**Comment by niemeyer** [comment]
+1. I've been trying to create an EKS cluster via the web console for a few days now precisely because I thought it would be straightforward to get started with it, but it's been extremely frustrating. Clearly there's something wrong with the configuration that prevents the node group from joining the cluster, but it's impossible to tell what it is. Logs don't say anything, and the console simply reports NodeCreationFailure after about one entire hour of silence on "Creating...".  I've been trying to tune configuration here and there slightly to see if I hit the right spot, but no luck so far. This really needs to be more clear.

**Comment by pgasca** [comment]
@niemeyer, I'm glad you were able to resolve the issue you experienced! As for documentation, we cover several considerations for NodeCreationFailure in the [Troubleshooting ](https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html) section. I discussed them with somebody who specializes in the VPC considerations for EKS.

Unfortunately, there's a huge variety of other potential issues people can run into depending on their particular environment. and there's no way to cover all cases in a way that would avoid readers needing to become intimately familiar with the [Networking](https://docs.aws.amazon.com/eks/latest/userguide/eks-networking.html) topic for proper configuration. To avoid overloading the troubleshooting entry, we would like to keep the text as is where readers can go through the three different links as needed. We'll keep an eye out for other trends that could be used to inform further rewrites of that troubleshooting entry.
