### ISSUE TITLE
Why still use "Slave"?

### ISSUE THREAD

**Issue by awsimaya** [awsdocs/amazon-eks-user-guide#41]
Could use "Worker" instead of the potentially unsettling word "Slave" in this document.

**Comment by nrdlngr** [comment]
Hi @awsimaya. I recognize that the word slave can be potentially unsettling, and I would love to remove it from this topic. However, since that terminology is hard coded into the manifests for the [guestbook-go](https://github.com/kubernetes/examples/tree/master/guestbook-go) example repository, I can't at this time. 

When the example manifests are updated to remove that language, I will follow suit. I'm closing this issue for now. Thanks for your suggestion.
