### ISSUE TITLE
EKS Worker nodes & public Ip address

### ISSUE THREAD

**Issue by frumania** [awsdocs/amazon-eks-user-guide#49]
I got feedback by an AWS partner, that the worker nodes, created by the cloud formation template are having a **public IP address** by default.
Shouldn't that be a parameter/setting?

See also

> To launch your worker nodes with the AWS Management Console
> https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html
> 
> Cloud Formation Script
> https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2019-02-11/amazon-eks-nodegroup.yaml
> ->
> "AssociatePublicIpAddress: true"

**Comment by nrdlngr** [comment]
I've passed this feedback on to the service team, and I've also added a note to the launch worker node workflow that says you can edit this parameter in the CloudFormation designer to disable public IP addresses for worker nodes.

**Comment by jimdial-aws** [comment]
As mentioned above, the documentation explains how to disable the default in the template, if desired, for self-managed node groups. A similar issue exists for managed node groups and is being tracked [here]( https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2019-11-15/amazon-eks-vpc-private-subnets.yaml). The issue has some recent dialog from our engineering team on the state of the public IP default. If you have further questions or comments on this default, then I encourage you to participate in that discussion. I'm closing this issue since nothing more can be done in the documentation at this time. Thank you for using Amazon EKS!
