### ISSUE TITLE
cannot upgrade kubectl to 1.21 , instead version always shows 1.16

### ISSUE THREAD

**Issue by rahulbreezo** [awsdocs/amazon-eks-user-guide#495]
I am installing kubectl in my buildspec as part of build pipeline using this https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html

First I installed 1.16 version , everything was fine at the first deployment of template using `kubectl apply ...`

Second time when pipeline started and tried to run `kubectl applly ....`  , I dont know but what reasone its taking more than 30 min in build while only few minutes when I do this in my local system.

So I figured kubectl version is different in build spec and in my local.

So I tried to install 1.21 version in codebuild buildspec

but no matter what I do , version always is 1.16. I am not able to upgrade it.

buidlspec kubectl install part:

```
  install:
    commands:
      # https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html
      - echo Installing app dependencies...

      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl

      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc

      - kubectl version --short --client
```

**Comment by pgasca** [comment]
@rahulbreezo, I went through these steps myself yesterday with a fresh install of kubectl, so the procedure should be working. There are a number of things that could possibly lead to the scenario you describe that would have to be covered as a support request instead of a documentation request.

It seems like you could have an older version of kubectl installed elsewhere that is conflicting with the newer version installation. Please try to find the older version and remove the binary manually. 

To get a list locations of kubectl, one way would be to do this:
```
cd /
sudo find . -name "kubectl"
```
I hope that helps. If removing the older kubectl doesn't work for you, please reach out to tech support:
https://aws.amazon.com/premiumsupport/knowledge-center/get-aws-technical-support/
