### ISSUE TITLE
Latest EKS Release missing

### ISSUE THREAD

**Issue by captn3m0** [awsdocs/amazon-eks-user-guide#603]
This recent change: https://github.com/awsdocs/amazon-eks-user-guide/commit/90c085170a9efdb9e0b646672885538dc713a145#diff- a7c93dd2867c005629f109bf0c19b25cedc17ecc732d860cfe4bc425b7d220b8 removed the latest version of kubernetes that is available for deployment on EKS clusters.

Tracking the page was the easiest way to get notified of new EKS point releases as of now. Now that the page has switched to just noting minor releases, this option is no longer available.

endoflife.date was using this page to track EKS version releases for eg: https://github.com/endoflife-date/release-data/blob/main/releases/eks.json, https://endoflife.date/amazon-eks

Please add this back.

**Comment by jimdial-aws** [comment]
The patch version was removed from that page because all that you pass (or is returned from the API) is the major.minor version. That's also all that's passed in when you create a cluster. The [platform versions](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/platform-versions.md) page includes the patch number for each Kubernetes version, and is really the better place to pull the information from. It also shows a version history based on the Kubernetes version in each platform release.

**Comment by captn3m0** [comment]
Thanks, this helps.
